### ISSUE TITLE
text is unreadable in dark theme

### ISSUE THREAD

**Issue by nilmerg** [gipfl/diff#2]
I'd add `color: @text-color-inverted;` [here](https://github.com/gipfl/diff/blob/master/public/css/diff.less#L34).

**Comment by lippserd** [comment]
@Thomas-Gelf: This still has to be fixed, else diffs are not readable.

**Comment by Thomas-Gelf** [comment]
@lippserd: I tried it out -> while `@text-color-inverted` works fine with the new dark mode, it becomes completely unusable in light mode, in all legacy themes and in web 2.8/2.9. Do you have any suggestion? I have no good idea for how to address this.

**Comment by lippserd** [comment]
@nilmerg @flourish86 Can you please help here?

**Comment by nilmerg** [comment]
Well, one could also try `color: black;` in the same location.
